modules::export("RULES")
RULES <- list()
RULES$MARRIAGE$AGE_LOWER_BOUND <- 16L
RULES$MARRIAGE$AGE_UPPER_BOUND <- 60L
RULES$COHABITATION$AGE_LOWER_BOUND <- 16L
RULES$COHABITATION$AGE_UPPER_BOUND <- 60L
RULES$DIVORCE$AGE_LOWER_BOUND <- 16L
RULES$DIVORCE$AGE_UPPER_BOUND <- 60L
RULES$GIVE_BIRTH$AGE_LOWER_BOUND <- 16L
RULES$GIVE_BIRTH$AGE_UPPER_BOUND <- 49L
RULES$LEAVE_HOME$AGE_LOWER_BOUND <- 18L
RULES$LEAVE_HOME$AGE_UPPER_BOUND <- 35L

modules::export("IND")
IND <- dymiumCore:::IND
IND$ID_COLS <- c("partner_id", "father_id", "mother_id")
IND$LABOUR_FORCE_STATUS$EMPLOYED <- "employed"
IND$LABOUR_FORCE_STATUS$UNEMPLOYED <- "unemployed"
IND$LABOUR_FORCE_STATUS$NOT_IN_THE_LABOUR_FORCE <- "not in the labour force"
IND$LABOUR_FORCE_STATUS$NOT_APPLICABLE <- "not applicable"
IND$EDUCATION$NOT_APPLICABLE <- "not applicable"
IND$EDUCATION$YEAR_11_AND_BELOW <- "year 11 and below"
IND$EDUCATION$YEAR_12_OR_EQUIVALENT <- "year 12 or equivalent"
IND$EDUCATION$CERTIFICATE_LEVEL <- "certificate level"
IND$EDUCATION$GRADUATE_DIPLOMA_AND_GRADUATE_CERTIFICATE_LEVEL <- "graduate diploma and graduate certificate level"
IND$EDUCATION$ADVANCED_DIPLOMA_AND_DIPLOMA_LEVEL <- "advanced diploma and diploma level"
IND$EDUCATION$BACHELOR_DEGREE_LEVEL <- "bachelor degree level"
IND$EDUCATION$POSTGRADUATE_DEGREE_LEVEL <- "postgraduate degree level"

modules::export("EVENT")
EVENT <- list()
EVENT$MARRIAGE <- "MARRIAGE"
EVENT$MARRIAGE_FROM_COHABITATION <- "MARRIAGE_FROM_COHABITATION"
EVENT$DIVORCE <- "DIVORCE"
EVENT$SEPARATION <- "SEPARATION"
EVENT$WIDOWED <- "WIDOWED"
EVENT$LEFT_HOME <- "LEFT_HOME"
EVENT$COHABITATION <- "COHABITATION"
EVENT$BREAKUP <- "BREAKUP"
EVENT$GAVE_BIRTH <- "GAVE_BIRTH"
EVENT$DEATH <- "DEATH"
EVENT$LEFT_HOUSEHOLD <- "LEFT_HOUSEHOLD"
EVENT$JOINED_HOUSEHOLD <- "JOINED_HOUSEHOLD"
EVENT$JOINED_EXISTING_HOUSEHOLD <- "JOINED_EXISTING_HOUSEHOLD"
EVENT$JOIN_PARTNER_HOUSEHOLD <- "JOIN_PARTNER_HOUSEHOLD"
EVENT$JOINED_PARTNER_HOUSEHOLD <- "JOINED_PARTNER_HOUSEHOLD"
EVENT$CREATE_NEW_HOUSEHOLD <- "CREATE_NEW_HOUSEHOLD"
EVENT$IMMIGRATED <- "IMMIGRATED"
EVENT$EMIGRATED <- "EMIGRATED"
EVENT$MOVED_WITH_PARENT <- "MOVED_WITH_PARENT"