# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial
language: R
sudo: false
cache: packages
cran: https://cran.rstudio.com/
warnings_are_errors: true
r_check_args: '--as-cran'

before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown#1276")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true
  
after_success:
  - Rscript -e 'covr::codecov()'
